# Generated by Django 5.2.6 on 2025-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='career_goal',
            field=models.CharField(default='Undecided', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_skills',
            field=models.ManyToManyField(blank=True, to='auth_app.skill'),
        ),
    ]
